### PR TITLE
Calendar creation

### PR DESCRIPTION
**Pull request by ChaseDitt**
<!Pull Request Template>

## Description

In this branch I created the view for the calendar where a user(eventually an admin but at the moment anyone) can go on and view each day and how many people are allowed to be absent and how many people have requested it off. The user can modify how many people are allowed to be off and also see and indicator if that amount has been surpassed in the amount of requests. 

## Tests
Added selenium tests to test all the functionality of the javascripts to make sure they are operating as expected
## UI Changes

image

## Issues

1. Still need to make it so only admins can see the page
2. Will probably be bugs when we implement other features with it so watch out for that

## Additional Notes

_Add any other information about the PR here._

---

### CODE REVIEW

**Comment by chazwilmot** [comment]
Two merge conflicts with forms/models and forms/tests

**Review by chazwilmot — APPROVED** [review]
LGTM

**Review by chazwilmot — APPROVED** [review]
LGTM

**Review by teckenrod — APPROVED** [review]
LGTM

**Pull request merged**
