### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chazwilmot**
<!Pull Request Template>

## Description

Removal of docker and some unused areas

### CODE REVIEW

**Review by teckenrod — APPROVED** [review]
LGTM

**Review by teckenrod — APPROVED** [review]
Good removal of docker info, will want to add more startup info later on

**Comment by chazwilmot** [comment]
Agreed, need to look into User and Developer Docs

**Review by smblackwll — APPROVED** [review]
I don't see any reason not to merge these issues in, but we may want to link the dev and user docs in the readme in the future.

**Pull request merged**
