### PR TITLE
Workflow functionality finished

### PR DESCRIPTION
**Pull request by smblackwll**
## Description

The full functionality for workflows are in - at least for Absence Request and Travel Authorization.
## Tests

Pytest Tests to check if the model is valid.
Cucumber Tests to test if the add/remove buttons work.

## UI Changes

New Management Dashboard UI
image
Has a separate section for each form.

The request UI now has a modified top bar:
image

All new workflows UI:
image

## Issues

This closes:
#170 
#169 
#164 
#85 
#71 

## Additional Notes

Any UI can change - if you have any questions just let me know.
---

### CODE REVIEW

**Comment by chazwilmot** [comment]
It is still failing the checks

**Comment by smblackwll** [comment]
Yeah - I accidently pushed before I finished fixing the tests. On the last few now.

**Comment by smblackwll** [comment]
Linking the failing actions from the #172 bug report here.

**Review by ChaseDitt — APPROVED** [review]
This looks good and I was here in person for the fix

**Review by teckenrod — APPROVED** [review]
Workflow feature looks good, I will fill in some gaps in coverage, glad we got past the action issue

**Pull request merged**
